spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ed8b6790f78a6a4ddafca967ff14da73
            client-secret: hcG8hJYUMU5HfdJxSy7pYRONkSG7ypbF
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: db6lxVLYFEruQrKlqXzGKsuygzX0h/6lJHVFNi6AArb40pCOErtYH8sStEvMISKr9J1HlN0ZTx25vNrXa6Rc2A==
  expire:
    access-token: 1
    refresh-token: 24
