#spring:
#  datasource:
#    url:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@0000
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true



