name: CI/CD for Spring Boot and React

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Disk Usage
        run: df -h

      - name: Clean up Docker space
        run: |
          docker system prune -af --volumes
          docker builder prune -af

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reservation-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/reservation-app:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy using Docker Compose
        run: |
          docker compose down || true
          docker compose up -d
        env:
          RDS_URL: ${{ secrets.RDS_URL }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
