name: CI/CD for Spring Boot and React

on:
  push:
    branches:
      - main

jobs:
  # 1. Build Docker Image Job
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reservation-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/reservation-app:latest

  # 2. Deploy Docker Image Job
  deploy:
    runs-on: self-hosted
    needs: build # build Job이 성공해야 실행
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy using Docker Compose
        run: |
          export DB_URL=${{ secrets.RDS_URL }}
          export DB_USERNAME=${{ secrets.RDS_USERNAME }}
          export DB_PASSWORD=${{ secrets.RDS_PASSWORD }}
          export JWT_SECRET=${{ secrets.JWT_SECRET }}
          export KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
          export KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
          docker compose -f docker-compose.yml up -d
