name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository Checkout
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Set up Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache Gradle Packages
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Build Backend with Gradle
      - name: Build Backend with Gradle
        run: |
          ./gradlew clean build --stacktrace
          ls -al build/libs/

      # 5. Build Frontend
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          CI=false npm run build
          ls -al build/

      # 6. Ensure Static Directory Exists
      - name: Ensure Static Directory Exists
        run: mkdir -p src/main/resources/static

      # 7. Debug Directories
      - name: Debug Directories
        run: |
          ls -al src/main/resources/
          ls -al frontend/build/

      # 8. Copy Frontend to Backend Static Resources
      - name: Copy Frontend to Backend Static Resources
        run: cp -r frontend/build/. src/main/resources/static/

      # 9. Build Docker Image
      - name: Build Docker Image
        run: docker build -t sjnnj/reservation:latest .

      # 10. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 11. Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push sjnnj/reservation:latest

      # 12. Stop and Remove Existing Container
      - name: Stop and Remove Existing Container
        run: |
          docker ps -q --filter "name=reservation" | xargs -r docker stop
          docker ps -aq --filter "name=reservation" | xargs -r docker rm

      # 13. Remove Old Docker Images
      - name: Remove Old Docker Images
        run: |
          docker images -q --filter "dangling=true" | xargs -r docker rmi
          docker images -q sjnnj/reservation --filter "dangling=false" | xargs -r docker rmi

      # 14. Run New Docker Container
      - name: Run New Docker Container
        run: |
          docker run -d -p 8080:8080 --name reservation \
            -e RDS_URL=${{ secrets.RDS_URL }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            sjnnj/reservation:latest
